### ISSUE TITLE
Update README with one-liner project descriptions

### ISSUE THREAD

**Issue by rshriram** [istio-ecosystem/README#1]
@istio-ecosystem/readme team (members of the org)
 Please add a one line description of your respective projects
 The README will service as a directory that lists the projects and details regarding the project.

**Comment by ZackButcher** [comment]
See https://github.com/istio-ecosystem/README/issues/2, https://github.com/istio-ecosystem/README/issues/3

**Comment by linsun** [comment]
https://github.com/istio-ecosystem/README/pull/4
