### ISSUE TITLE
Request new repo for external SDS server

### ISSUE THREAD

**Issue by zhlsunshine** [istio-ecosystem/README#10]
**Q: Name of the repo**
**A：**`hsm-sds-server`

**Q: Description of the repo**
**A:** This repo follows the SDS extension standard of Envoy and implements an external SDS server via more secure solution which is known as `Hardware Security Module`(HSM). By using this repo, 

1. User can maintain the credentials for workloads managed by Istio/Envoy in more secure scenario via external SDS server
2. Besides supporting management for new credentials, it also allows user to upload existing credentials and manages them in higher security level
3. This external SDS server can be used for both gateways and workload sidecars to provide their credential information

**Q: How is the repo related to the Istio project?**
**A:** There are at least 3 proposals of Istio community related to this repo as below:
  The Secret Discovery Service provided by `istiod` can be used to obtain the credentials from Kubernetes secrets for user's workloads in Istio. 
However, referencing credentials from other sources instead Kubernetes Secrets is a meaningful requirement for Istio users, for example, Istio user may want to maintain the workload's credentials by themselves, it means that Istio sidecar can fetch the credentials from alternative backends which can be an external SDS/HTTP backends in safety mode. Below are some related proposals in Istio community:
  1. [Istio Envoy mTLS Private Key Protection with HSM](https://docs.google.com/document/d/1mtMgbNUr4y8_4uKVSNjJYrJS-lUttkNwEknDNBBLD8E/)
  2. [Extending credentialName storage backends](https://docs.google.com/document/d/1DEUkk0ocrD_oAH0h8TOUIC94Lf8msDXJb9lyNWlX_Ho/)
  3. [External SDS server Support for gateways](https://docs.google.com/document/d/1YaY67cAfK1naaUuRx8mKHKVKq8fjkP3CXNq-W3MCpLQ/)
  4. [Auth for Istiod SDS](https://docs.google.com/document/d/1nwTh2g7FgdkC8suc3SHZ5le_4Rkm8YvLY8Cgah4cm-I/)
  5. [Protect the private keys in Envoy with Intel SGX](https://docs.google.com/document/d/1Nk171M5hGdxMfMTf573HC2Slp4zPBViZNnk18OTqlRc/edit#heading=h.eqfw9z6inpip)
 
**Q: What are the GitHub ids of the initial admins of the repo?**
**A:** There are 3 initial admins: `Chen-Xintong`, `irisdingbj` and `zhlsunshine`

**Comment by zhlsunshine** [comment]
Hi @linsun, @howardjohn and @costin,  could you please help to create a repo described above when you are available? Thanks in advance!

**Comment by linsun** [comment]
Is the license for the repo clear?  please clarify

**Comment by linsun** [comment]
Steve confirmed with me ASL 2.0 license offline via slack

**Comment by linsun** [comment]
https://github.com/istio-ecosystem/hsm-sds-server/ - sorry for the delay, been travelling this week. @zhlsunshine, i'll close this for now.
