### ISSUE TITLE
Need  a repo for consul mcp

### ISSUE THREAD

**Issue by zhaohuabing** [istio-ecosystem/README#9]
As we agreed in the Network Working Group Meeting, we need to create a new repo to accommodate the consul mcp adapter.

Meeting note https://docs.google.com/document/d/1xHy2jQ8oiwMponMVY2zJr2eUAmHW_Hi9JK42a7cg5Pc/edit

**Comment by linsun** [comment]
repo is created - https://github.com/istio-ecosystem/consul-mcp/

you are added as a maintainer for the repo.

**Comment by zhaohuabing** [comment]
Thanks @linsun
